version: '3.9'
#python manage.py collectstatic --noinput && 
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 #gunicorn --bind 0.0.0.0:8000 overallblog.wsgi:application
    volumes:
      - .:/app
    expose:
      - 8000
    ports: 
      - 8000:8000
    restart: always